import baseConfig from '../../eslint.config.mjs';

export default [
  ...baseConfig,
  {
    // Generated by the `codegen` target from apps/api/openapi.json.
    ignores: ['**/out-tsc', 'src/lib/generated.ts'],
  },
];
